language: cpp
sudo: true
compiler:
- g++
os:
- linux
addons:
  apt:
    packages:
    - xvfb
before_install:
- sudo apt-get update && sudo apt-get install libglfw3-dev libgles2-mesa-dev
- sudo apt-get install libboost-all-dev
- |
  if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
    mkdir -p external/cmake
    pushd external/cmake
    wget https://cmake.org/files/v3.8/cmake-3.8.0-Linux-x86_64.sh
    chmod +x cmake-*-Linux-x86_64.sh
    ./cmake-*-Linux-x86_64.sh --exclude-subdir --skip-license
    export PATH="${PWD}/bin:$PATH"
    cmake -version
    popd
  else
    if ! brew ls --version cmake &>/dev/null; then brew update; brew install cmake; fi
  fi
install:
- export DISPLAY=':99.0'
- Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
before_script:
- cd GCanvas/core/test/w3c &&mkdir build
- npm i && node app.js
- cd ../../../../
script:
- cd GCanvas/core/test/linux && mkdir build && cd build && cmake ../ && make
- cp ../util/font/wqy-microhei.ttc ./  &&   cp ../util/font/.fontcache  ./
- "./gcanvasTest"
- cat ./result.txt
- cd ../../../../../
deploy:
  provider: releases
  api_key:
    secure: p8ueR7uzNxkCOXF1D9EGd/Tjy7hNAbhYBzOKN0Kze96aqnBmb07KrR0mZXDlvYRe2hKD7fYs2hbH56RlL/sl/98RxZG8SCnmpmUvEs3ztjkExyBNGHq2mYfyfmcjzmsDt0IMJnJdhS7IjEGTc4lkndN/h6oGw77tcC6Vp7yT4ImVukhYMZVE/TuKLzgf7GXLuFjHCdJP8BFfmXQ1TqtCVdDW6FLHQe/GB1kUUtyRVf/hf+8pxnJM34D/eI/jT8IBygYpKrzfpeYO4ovKUf+G+95XEjpws1CwlCuLMWDDZEG0MM/GhcDrJiKOt8ZGUxm2Asd1xwd5Wj1/6WyaeOHsYr+wtUjYGRwokOepoqO+Hjk/jjMh+3GDfYdI/kG2oRZIgmNZtRpzA6NjZy7W60ocKpubpPTAx43oqMDO7DhiabWgYduZPzREEbqhm2d5IMWHY/H62HblCtrfcWeJH/8fCSgawWV6wUQntkcf7O5jIyqzXFzKrMm4nRUKHIj5yb+GXyqkqODFiegyKYfPVNDwzl/Mw9p9oaKTwq5ZAJZ6KdA4eU0+Z/U08jTyvbIUdpIN5usfBT9ib8zrXpJHlcCbDmSHv9vHzrg9fhy9qTydP8CfIWNiuJ152uw8Eu320AmPBm+FhnKqUNvqGjF+ZbskBM+NFWQDBmyIX3z2OmLBGrw=
  file: ./GCanvas/core/test/linux/build/result.txt
  on:
    repo: alibaba/GCanvas
    branch: master
    tags: true
